config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]
  get 'homes/about' => 'homes#about' , as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

 has_many :users, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # belongs_to :book
  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def new
   @book = Book.new(book_params)
 end

 def edit
  @user = User.find(params[:id])
 end

 def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
 end

 def index
  @book=Book.new
  @books=Book.all
  @user=current_user
 end

 def show
  @book=Book.new
  @books=Book.all
  @user=current_user
 end

 def destroy
 end

 private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @user=current_user
end

def edit
  @user = User.find(params[:id])
end

def show
  @book=Book.new
  @books=Book.all
  @user=current_user
end

def update
  @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
end

private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to post_images_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
    <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
    </table>
<div class="row">
   <a>
    <%= link_to edit_user_path(@user.id) ,class: 'btn btn-outline-secondary btn-block' do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
</a></div>

  <h1>New book</h1>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

</div>

app/views/books/index.html.erb
<main>
  <div class="container">
    <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>

    <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
    </table>

<div class="row">
   <a>
    <%= link_to edit_user_path(@user.id) ,class: 'btn btn-outline-secondary btn-block' do %>
  <!--<a class="btn btn-outline-secondary btn-block edit_user_69297" href="/users/69297/edit">-->
     <i class="fas fa-user-cog"></i>
     <% end %>
</a></div>

  <h1>New book</h1>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>

<table class="table table-hover table-inverse">

  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= image_tag @user.get_profile_image(100,100) %>
        </td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

</main>

app/views/books/show.html.erb
<main>
<div class="container">
<div class="row">
<%= render 'list', books: @books %>

<div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		    <% @books.each do |book| %>
  		    <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td>
          <%= link_to "Edit", edit_book_path(book.id) %>
          </td>
           <td>
           <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %>
          </td>

        </tr>
         <% end %>
      </tbody></table>
    </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to
     <i class="fas fa-book"></i>
    <strong>Bookers</strong>!</h1>
  </div>
</div>
</main>

app/views/homes/top.html.erb
<!--<header>-->
<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
<!--    <div class="container">-->
<!--      <a class="navbar-brand" href="/"><span>Bookers</span></a>-->
<!--      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
<!--      <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">-->
<!--        <ul class="navbar-nav ml-auto">-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/"></a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/home/about"></a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_up"></a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_in"></a>-->
<!--          </li>-->
<!--        </ul>-->
<!--      </div>-->
<!--    </div>-->
<!--  </nav>-->
<!--</header>-->
<main>
    <p id="notice"></p>
    <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">


<h1>
    welcome to
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>
    !!
</h1>

<p>
    In
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>
    ,
</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
    </div>
    <div class="row">
      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
    </div>
</div>
</div>
</div>
</div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to "/books/:id" do %>
              <i class="fas fa-home"></i>
              Home
            <% end %>
          </li>

          <li>
            <%= link_to "/users" do %>
               <i class="fas fa-users"></i>
              Users
            <% end %>
          </li>

          <li>
            <%= link_to "/books" do %>
                <i class="fas fa-book-open"></i>
              Books
            <% end %>
          </li>

            <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>
              Log out
            <% end %>
            </li>

           <% else %>
           <li>
            <a>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
              Home
            <% end %>
            </a>
          </li>
          <li>
            <a>
             <%= link_to about_path do %>
               <i class="fas fa-link"></i>
              About
            <% end %>
            </a>
          </li>
          <li>
            <a>
               <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i>
              Sign up
            <% end %>
            </a>
          </li>
          <li>
            <a>
              <%= link_to new_user_session_path do %>
                 <i class="fas fa-sign-in-alt"></i>
              Log in

            <% end %>
            <% end %>
        </ul>
      </div>
      </div>
      </nav>
    <!--% if user_signed_in? %>-->
    <!--  <li>-->
    <!--    %= link_to "ログアウト", destroy_user_session_path, method: :delete %>-->
    <!--  </li>-->
    <!--% else %>-->
    <!--  <li>-->
    <!--    %= link_to "新規登録", new_user_registration_path %>-->
    <!--  </li>-->
    <!--  <li>-->
    <!--    %= link_to "ログイン", new_user_session_path %>-->
    <!--  </li>-->
    <!--% end %>-->
    </header>
    <%= yield %>
    <footer>
      <div class ="container mt-5">
        <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<!--<main>-->
<!-- <p id="notice"></p>-->
<!--  <div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">-->
<!--    <h2>User info</h2>-->
<!--    <form enctype="multipart/form-data" action="/users/69571" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off"><input type="hidden" name="authenticity_token" value="hI2lXOayny8L180dvCrkwmgY49vq91l6FBzWEEA0Y61XYxOaNBjWFc7vXUTTGkuUhE3aUzkf56erNUzGO9jE9w" autocomplete="off">-->

<!--      <div class="form-group">-->
<!--        <label for="user_name">Name</label>-->
<!--        <input class="form-control name" type="text" value="柏　パクチー" name="user[name]" id="user_name">-->
<!--      </div>-->
<!--     <div class="form-group">-->
<!--        <label for="user_image">Image</label>-->
<!--        <input class="form-control-file user_image" accept="image/*" type="file" name="user[profile_image]" id="user_profile_image">-->
<!--      </div>-->
<!--      <div class="form-group">-->
<!--        <label for="user_introduction">Introduction</label>-->
<!--        <textarea class="form-control introduction" name="user[introduction]" id="user_introduction"></textarea>-->
<!--      </div>-->
<!--      <div class="form-group">-->
<!--        <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">-->
<!--      </div>-->
<!--    </form>-->
<!--    </div>-->
<!--  </div>-->
<!--  </div>-->
<!--</main>-->
<main>
  <p id="notice"></p>
  <div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model: @user do |f| %>
 <div>
  <label for="inputName">Name</label>
  </div>
  <div>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  </div>
  <div>
  <label for="inputImage">Image</label>
  </div>
  <div>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  </div>
  <div>
  <label for="inputImage">Introduction</label>
  </div>
  <div>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction"%>
  </div>

  <div>
  <%= f.submit "Update User" %>
  </div>
<% end %>
</div>
</div>
</div>
</main>

<!--<main>-->
<!--  <p id="notice"></p>-->
<!--  <div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">-->
<!--    <h2>User info</h2>-->
<!--    <form enctype="multipart/form-data" action="/users/69668" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off"><input type="hidden" name="authenticity_token" value="4KqrNeNSfWl9RoD3RSRNp2qreJu3KgExvaLUvX-HFz7s4bY5_rD4E_82XrkhE-0zrK2Ucc7gUzHBzcyVV3GslA" autocomplete="off">-->

<!--      <div class="form-group">-->
<!--        <label for="user_name">Name</label>-->
<!--        <input class="form-control name" type="text" value="柏 パク１" name="user[name]" id="user_name">-->
<!--      </div>-->
<!--     <div class="form-group">-->
<!--        <label for="user_image">Image</label>-->
<!--        <input class="form-control-file user_image" accept="image/*" type="file" name="user[profile_image]" id="user_profile_image">-->
<!--      </div>-->
<!--      <div class="form-group">-->
<!--        <label for="user_introduction">Introduction</label>-->
<!--        <textarea class="form-control introduction" name="user[introduction]" id="user_introduction"></textarea>-->
<!--      </div>-->
<!--      <div class="form-group">-->
<!--        <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">-->
<!--      </div>-->
<!--</form>  </div>-->
<!--</div>-->
<!--</div>-->
<!--</main>-->

app/views/users/index.html.erb
<main>
<div class="container">
<div class="row">
<%= render 'books/list', books: @books %>

<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= image_tag @user.get_profile_image(100,100) %></td>
        <td><%= @user.name %></td>
        <td><%=link_to "Show" ,user_path(@user.id) %></td>
      </tr>


  </tbody>
</table>

    </div>






</div>
</div>
</main>

app/views/users/show.html.erb
<main>
<div class="container">
<div class="row">
<%= render 'books/list', books: @books %>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= image_tag @user.get_profile_image(100,100) %>
        </td>
        <td><%= link_to book.title,book_path(@user.id) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>

</div>
</div>
</main>